import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
/*----------------importacion de estilos locales-----------------------*/
import "./styles/globals.css";
/*----------------importacion de estilos locales-----------------------*/
/*----------------importacion de estilos Externas-----------------------*/
import 'bootstrap/dist/css/bootstrap.min.css';
/*----------------importacion de estilos Externas-----------------------*/

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "Register Coppel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
